repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
  # # ===
  # # Terraform config may fail in CI because I don't think terraform/opentofu
  # # is installed on the pre-commit.ci runners
  # # ===
  # - repo: https://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.105.0
  #   hooks:
  #     - id: terraform_tflint
  #     - id: terraform_fmt
