name: Plan changes to GitHub Teams Membership

on:
  pull_requests:
    branches:
      - main

env:
  GCLOUD_VERSION: 553.0.0
  TOFU_VERSION: 1.11.4

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v3
        with:
          project_id: 'my-project'
          credentials_json: ${{ secret.GCP_SA_CREDS }}

      - uses: google-github-actions/setup-gcloud@v3
        with:
          version: ${{ env.GCLOUD_VERSION }}

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.TOFU_VERSION }}

      - working-dir: tf-config
        run: tofu init
      
      - working-dir: tf-config
        run: tofu plan
