name: Plan and apply changes to GitHub Teams Membership

on:
  push:
    branches:
      - main
    paths:
      - teams.yaml
      - tf-config/**
  pull_request:
    branches:
      - main
    paths:
      - teams.yaml
      - tf-config/**

env:
  GCLOUD_VERSION: 553.0.0
  TOFU_VERSION: 1.11.4

jobs:
  plan-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: google-github-actions/auth@v3
        with:
          project_id: "supple-tracker-380219"
          credentials_json: "${{ secrets.GCP_SA_CREDS }}"

      - uses: google-github-actions/setup-gcloud@v3
        with:
          version: ${{ env.GCLOUD_VERSION }}

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.TOFU_VERSION }}

      - working-directory: tf-config
        run: tofu init

      - working-directory: tf-config
        run: tofu workspace select -or-create main
        env:
          TF_VAR_github_token: "${{ secrets.GH_TOKEN }}"

      - working-directory: tf-config
        run: tofu plan
        env:
          TF_VAR_github_token: "${{ secrets.GH_TOKEN }}"

      - if: github.event_name != 'pull_request'
        working-directory: tf-config
        run: tofu apply -auto-approve
        env:
          TF_VAR_github_token: "${{ secrets.GH_TOKEN }}"
