name: Validate config files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      team-matrix: ${{ steps.generate-matrix.outputs.teams-matrix }}
    steps:
      - uses: actions/checkout@v6

      - id: generate-matrix
        shell: bash
        run: |
          # Initialize the list
          list="["

          # Loop over all .yaml files in ./teams
          first=true
          for file in ./teams/*.yaml; do
              # Extract filename without path and .yaml extension
              filename=$(basename "$file" .yaml)
              
              # Add comma separator for all but the first item
              if [ "$first" = true ]; then
                  list="${list}{\"team\": \"$filename\"}"
                  first=false
              else
                  list="${list}, {\"team\": \"$filename\"}"
              fi
          done

          # Close the list
          list="${list}]"

          # Output the result
          echo "teams-matrix=${list}" >> "$GITHUB_OUTPUT"

  validate-yaml:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix:
        include: "${{ fromJSON(needs.generate-matrix.outputs.team-matrix) }}"
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - run: |
          python -m pip install -U pip
          python -m pip install jsonschema ruamel.yaml typer

      - run: |
          python scripts/validate-yaml.py teams/${{ matrix.team }}.yaml teams.schema.yaml

  tofu-lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: terraform-linters/setup-tflint@v6

      - uses: dflook/tofu-fmt@v2
        with:
          path: tf-config

      - run: tflint --fix
        working-directory: tf-config

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Run tofu fmt and lint"
